version: "3"
services:

  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    volumes:
      - ../:/Cactus
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  backend:
    container_name: cactus-webserver
    build: .
    volumes:
      - ../:/Cactus
    ports:
      - 3001:3001
    environment:
      - USER=root
volumes:
  backend:
