version: "3"
services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - ../:/Cactus
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 3002:3002
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  backend:
    build: .
    ports:
      - 3001:3001
    environment:
      - USER=root
volumes:
  backend:
